### ISSUE TITLE
Realtime Database emulation data view have child spacing issue

### ISSUE THREAD

**Issue by SrBrahma** [firebase/firebase-tools-ui#421] opened 2020-11-17 19:58 UTC
### [REQUIRED] Environment info

**firebase-tools:** 8.16.2

**Platform:**

### [REQUIRED] Test case
I can't make one right now.

### [REQUIRED] Steps to reproduce
1) Emulate a project which uses Realtime Database
2) Have at least 2 items under same parent, one that have children and other that doesn't
3) They aren't properly aligned, made me think that one was a child of the other.

### [REQUIRED] Expected behavior
Proper alignment

### [REQUIRED] Actual behavior
![Captura de tela de 2020-11-17 16-43-33](https://user-images.githubusercontent.com/28177550/99440093-d2480a80-28f4-11eb-936d-e073942e74cf.png)
`lU` seems to be a child of `l` because it's not properly aligned.
Opening `l`, looks worse.
![Captura de tela de 2020-11-17 16-59-46](https://user-images.githubusercontent.com/28177550/99441227-5bac0c80-28f6-11eb-8cd0-a996151ade2d.png)

Happened on Firefox, Ubuntu.

**Comment by yuchenshi** [comment] 2020-11-18 17:36
Duplicate of #261.

But please weigh in on the discussion there.

**Closed by yuchenshi** 2020-11-18 17:36 UTC

**Comment by yuchenshi** [comment] 2020-11-18 17:38
Duplicate of #261
