### ISSUE TITLE
GitHub Codespaces Firebase Firestore UI Emulator Whitescreen of Death Error

### ISSUE THREAD

**Issue by gregv** [firebase/firebase-tools-ui#874] opened 2022-12-02 16:55 UTC
**Describe the bug**
Firestore Component does not render correctly when ran within GitHub Codespaces.
Video: https://youtu.be/ZSifwz9Gt4M

**To Reproduce**
1. Start Forestore emulator + UI `firebase emulators:start --import 2022-11-20T02\:56\:20_12843/ --project test-ohack-dev`
2. Make port 4000 public within GitHub Codespaces to fix any CORS issues
2. Open Firestore UI in browser
3. Under "Firestore emulator" click "Go to emulator"
4. See error (white screen)

**Expected behavior**
Should open Firestore emulator UI

**Screenshots**
https://youtu.be/ZSifwz9Gt4M

![Screen Shot 2022-12-02 at 9 55 09 AM](https://user-images.githubusercontent.com/6913307/205344574-5ddf608c-2be1-42b6-9192-649e88b7ff15.png)

**Desktop (please complete the following information):**
N/A - this is running in Github codespaces

**Smartphone (please complete the following information):**
N/A - this is running in Github codespaces

**Additional context**
firebase.json
```
{  
  "emulators": {  
    "firestore": {
      "host": "0.0.0.0",
      "port": 8080
    },
    "ui": {
      "enabled": true
    },
    "singleProjectMode": true
  },
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  }
}
```

I'm loading sample test data via this `firebase-export-metadata.json` that runs fine on my local laptop
```
{
  "version": "X.X.X",
  "firestore":
  {
    "version": "X.XX.X",
    "path": "2022-11-20T02:56:20_12843",
    "metadata_file": "2022-11-20T02:56:20_12843.overall_export_metadata"
  }
}
```

`firestore.rules` (default)
```
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      // This rule allows anyone with your database reference to view, edit,
      // and delete all data in your database. It is useful for getting
      // started, but it is configured to expire after 30 days because it
      // leaves your app open to attackers. At that time, all client
      // requests to your database will be denied.
      //
      // Make sure to write security rules for your app before that time, or
      // else all client requests to your database will be denied until you
      // update your rules.
      allow read, write: if request.time < timestamp.date(2022, 12, 20);
    }
  }
}
```

`firestore.indexes.json` (default)
```
{
  "indexes": [],
  "fieldOverrides": []
}
```

**Comment by hsuabina** [comment] 2023-01-16 14:20
I'm getting the same error, we were running the Firestore UI within a docker container fine until a recent refactor of one of our repositories to use npm workspaces and turborepo.

Still not sure what's wrong here.

**Comment by yuchenshi** [comment] 2023-02-14 22:04
Duplicate of #912

**Closed by yuchenshi** 2023-02-14 22:04 UTC

**Comment by jeremytondo** [comment] 2023-10-31 16:13
I'm curious. Has anyone actually got this working with codespaces? #912 helped, but I still can't get passed some CORS and Websocket errors. So, while I can load and use the UI, the Firestore section will not load.

**Comment by Skarvion** [comment] 2024-05-09 12:27
@jeremytondo Have you ensure that you forward the port for the websocket other than the ones for the services? It should be listed as extra port

**Comment by jeremytondo** [comment] 2024-05-10 18:34
@Skarvion Yeah, I went through and made sure that all ports being used were forwarded. I haven't tried this in awhile though as I decided to find a solution other than Code Spaces.

**Comment by ezequieltejada** [comment] 2024-06-16 10:42
> @Skarvion Yeah, I went through and made sure that all ports being used were forwarded. I haven't tried this in awhile though as I decided to find a solution other than Code Spaces.

@Skarvion May I ask which solution you chose instead of Codespaces?

**Comment by Skarvion** [comment] 2024-06-16 12:59
> > @Skarvion Yeah, I went through and made sure that all ports being used were forwarded. I haven't tried this in awhile though as I decided to find a solution other than Code Spaces.
> 
> @Skarvion May I ask which solution you chose instead of Codespaces?

Tagged the wrong person, should be jeremy

**Comment by ezequieltejada** [comment] 2024-06-17 08:59
> > > @Skarvion Yeah, I went through and made sure that all ports being used were forwarded. I haven't tried this in awhile though as I decided to find a solution other than Code Spaces.
> > 
> > 
> > @Skarvion May I ask which solution you chose instead of Codespaces?
> 
> @ezequieltejada Tagged the wrong person, should be jeremy

My bad... @jeremytondo Which solution did you choose?

**Comment by jeremytondo** [comment] 2024-06-17 15:54
@ezequieltejada I ended up using VSCode server on my own hardware.

https://code.visualstudio.com/docs/remote/vscode-server

**Comment by ezequieltejada** [comment] 2024-06-17 17:34
> @ezequieltejada I ended up using VSCode server on my own hardware.
> 
> https://code.visualstudio.com/docs/remote/vscode-server

Thank you Jeremy!
