### ISSUE TITLE
Firestore Emulator UI doesn't have enough padding to edit items on small screens

### ISSUE THREAD

**Issue by thesandlord** [firebase/firebase-tools-ui#467] opened 2020-12-31 22:29 UTC
If you are trying to edit an item in the UI on a smaller screen and the item is at the bottom, there is not enough space on the popup to click save.

https://user-images.githubusercontent.com/8902396/103427237-7966c580-4b74-11eb-9c83-8527f118d062.mp4

**Comment by yuchenshi** [comment] 2021-01-06 19:00
Thanks for the bug and video! I've filed this internally as b/176910745. Help welcomed!

**Comment by thesandlord** [comment] 2021-01-19 03:50
Ah not sure if that comment was for me, I'm actually no longer at Google. Need to update my profile :)

Hacky fix for anyone looking at this issue, you can open up the inspector and change the style attribute from `top: 0` to `top:-300px` or another negative value as appropriate.

**Comment by yuchenshi** [comment] 2021-08-30 18:23
Thanks for looking into this! I think your idea to disable `scrollLock` is a great workaround while we look into the root cause. Let me see if I can get #636 merged.

**Closed** 2021-08-30 19:01 UTC
Labels: bug, good first issue, help wanted
