### ISSUE TITLE
Firebase auth emulator data export not working

### ISSUE THREAD

**Issue by PuruVJ** [firebase/firebase-tools-ui#406] opened 2020-11-03 04:23 UTC
When I add a new user in the newly released firebase auth emulator, and then shut down the emulator, started with command:

```bash
firebase emulators:start --export-on-exit --import em-data
``` 

the users are not retained when I restart the emulators, while firestore and RTDB are.

**Comment by yuchenshi** [comment] 2020-11-03 17:06
Duplicate of https://github.com/firebase/firebase-tools/issues/2749

**Closed by yuchenshi** 2020-11-03 17:06 UTC
