### ISSUE TITLE
Nested collection with parent document having no fields are not visible in firestore local emulator

### ISSUE THREAD

**Issue by manwithsteelnerves** [firebase/firebase-tools-ui#322] opened 2020-06-28 00:51 UTC
### [REQUIRED] Environment info

**firebase-tools:** : 8.4.3

**Platform:** : macOS

### [REQUIRED] Test case
Should show documents with nested collections greyed out similar to production firestore

### [REQUIRED] Steps to reproduce
1. Create a nested collection for a document where no fields exist through code
```
await admin.firestore().doc('players/123/addresses/456').set({street:'street'});
```

### [REQUIRED] Expected behavior
Document with 123 id should be visible (grey color) even if fields doesn't exist

### [REQUIRED] Actual behavior
Document with 123 id, is not shown in the emulator leading to difference between production and emulator. Also its pretty tough to debug this scenario!

**Comment by samtstern** [comment] 2020-06-29 12:33
@manwithsteelnerves since this is a UI issue (the document is stored it's just not being shown) I have transferred it to the UI repo.

**Comment by scottcrossen** [comment] 2020-06-29 20:47
Internal tracking bug: b/160175135

**Comment by yuchenshi** [comment] 2020-07-06 20:52
Duplicate of #273

**Closed by yuchenshi** 2020-07-06 20:52 UTC
