### ISSUE TITLE
Not displaying firestore documents added with a different projectId

### ISSUE THREAD

**Issue by bcye** [firebase/firebase-tools-ui#708] opened 2022-02-16 17:24 UTC
[The docs](https://firebase.google.com/docs/emulator-suite/connect_firestore#admin_sdks) say I can connect the admin sdk with any project id, but connecting with any other than the one of my live project, results in documents being created, but not displayed in the ui

**Comment by yuchenshi** [comment] 2022-02-16 18:23
Duplicate of #281

**Closed by yuchenshi** 2022-02-16 18:23 UTC
