### ISSUE TITLE
Firestore sub-collections with nonexistent parents are not showing in emulator

### ISSUE THREAD

**Issue by Joebayld** [firebase/firebase-tools-ui#273] opened 2020-05-25 03:24 UTC
### [REQUIRED] Environment info

**firebase-tools:**
8.4.0

**Platform:**
macOS 10.15.4

### [REQUIRED] Test case

I've found that when having nested collections in Firestore, they don't display on the web interface of the emulator unless parent documents contain data. 

### [REQUIRED] Steps to reproduce

```
// create some data in a nested collection without data in the document

db.collection('stripe')
.doc('6tSfMgrOCEOi3kj0IHRivd0ZCgX2')
.collection('subscriptions')
.doc('sub_123456789').set({
    status: "active"
})
```

### [REQUIRED] Expected behavior

On the production version of the data viewer, it displays empty documents in italics (to designate that there is no fields but sub-collections exist). Image below. 
<img width="1144" alt="Screen Shot 2020-05-24 at 8 02 36 PM" src="https://user-images.githubusercontent.com/9399317/82774616-2ec0e600-9dfa-11ea-9245-d94dabfad75b.png">

### [REQUIRED] Actual behavior

There is nothing to display on the UI and I cannot access child collections. If I set some dummy data on a document, the row will appear.

**Comment by 4mitabh** [comment] 2020-06-06 10:52
This is not merely an emulator UI issue. 

In certain cases, the behavior of writes is different between emulators and production.

### **Steps to reproduce:**
Perform the following write operation, on em **empty** database.
```
db.collection('one')
.doc('two')
.collection('three')
.doc('four').set({
    status: "active"
})
```

### **Expected behavior**
An empty document 'two., with a collection 'three' is created. This works perfectly in production.

### **Actual behavior:**
Neither document 'two' or 'three' are written into the emulated databse.

**Comment by yuchenshi** [comment] 2020-06-08 21:04
@4mitabh Just let me clarify: Even in production, the document `two` is not automatically created either. Reads to `two` always fail since `two` does not actually exist. There is no automatic cascading creation or deletion in Firestore.

The Firebase Console in production however shows an entry of "two" in the data viewer to help you navigate the database and find things under it. If you look closely, it also says "this document does not exist" in the panels to help clarify. This issue tracks the implementation of a similar feature to show a placeholder for such missing links in the Emulator UI.

**Comment by yuchenshi** [comment] 2020-07-06 20:54
I've escalated this internally as b/152785133 and we're actively trying to staff this fix. In the meantime, feel free to send us a Pull Request.

**Comment by tjlav5** [comment] 2020-09-15 16:58
#345 only partially addresses this... we can now navigate to a document whose parent(s) does not exist. Still need to add functionality to show the list of "missing docs" in italics in the UI-list.

**Comment by phenry20** [comment] 2021-02-11 07:07
Any Updates?

**Comment by edmondklai** [comment] 2021-02-15 00:04
I have an issue maybe related to this, when the document is empty and there is a sub-collection of documents.  I tried using the UI to add fields to the parent document.   

I get this error in the console.
```
Uncaught (in promise) Error: .set() on an existing document would delete other fields
    at api.tsx:51
    at c (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at r (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)
```

**Comment by yuchenshi** [comment] 2021-02-16 18:02
@phenry20 This should be fixed now. If you see otherwise, make sure to upgrade to the latest CLI and try again, and feel free to open a new bug if it still doesn't work for you.

@edmondklai I'm afraid you ran into a separate issue, #437. If you can reliably reproduce the issue, please add a comment there. Thanks!

**Closed by yuchenshi** 2021-02-16 18:02 UTC

**Comment by 28JayG** [comment] 2021-10-20 12:13
I am still facing this issue

**Comment by FrancescoBurchielli** [comment] 2022-05-13 15:58
hi everyone, any update on this? I do still face this issue now in May 2022, with latest Firebase CLI on Windows

**Comment by mozeryansky** [comment] 2022-05-14 08:09
> hi everyone, any update on this? I do still face this issue now in May 2022, with latest Firebase CLI on Windows

Use Supabase. It's 100000x better.

**Comment by johnberang12** [comment] 2022-08-20 14:58
im having the same issue..icant write on a subcollection but works perfectly on the actual firestore..whats the update on this.?

**Comment by johnberang12** [comment] 2022-08-20 15:02
why is this marked as solved then the issue is still not resolved

**Comment by braadworst** [comment] 2023-07-31 22:33
Is this being looked at? I am still experiencing this issue 01-08-2023

**Comment by mozeryansky** [comment] 2023-07-31 22:37
@braadworst I recommend switching to Supabase. No one should be using Firebase, it's just bad software.

**Comment by braadworst** [comment] 2023-07-31 22:46
> Supabase

Why blasting your commercial interests in a Github thread? Furthermore, Firebase ain't bad software and if I was ever considering Supabase your behavior have made me put it on the bottom of the list

**Comment by mozeryansky** [comment] 2023-07-31 23:12
@braadworst I don't have any commercial interest, I was giving a recommendation. I noticed that you are commenting on a 3-year-old bug that I once had, which is closed, yet you still have the same issue.

The reason Firebase is bad software is because they don't fix their bugs. Instead of going through all this trouble, as I and many others have experienced before, I highly recommend trying an alternative that actually works. It's entirely your choice whether you want to continue to use Firebase and resubmit issues.

**Comment by braadworst** [comment] 2023-07-31 23:55
So anyone having this problem, if you have a `:` in your id, the sub collections will not show in the emulator. There might be more special characters that trigger this behavior, so look for that in your ids. This sorts it out for me, everything works well, emulator shows the sub collections. 👍

**Comment by pepoospina** [comment] 2024-06-27 09:28
Why is this issue closed?

**Comment by mozeryansky** [comment] 2024-07-01 02:47
> Why is this issue closed?

Why are you using Firebase when there are so many better alternatives?

Firebase appears to just be in maintenance mode for a long time now, scroll up and see they don't care. Search the closed issues and you'll see they never resolve them. I've made numerous posts on SO where they used to respond, but they just say "that's how it works" and I'm pretty sure that guy in charge of that left years ago. Save yourself the headache. And before @braadworst gets into a pithy again, just know I have a personal interest in helping my fellow software engineers write better code, because one day I may end up using your product.

**Comment by mrspence** [comment] 2024-11-13 13:47
@mozeryansky This is not the place.

**Comment by Reptile-sandy** [comment] 2025-10-12 17:08
> I see. Thanks [@yuchenshi](https://github.com/yuchenshi) for the clarification.





https://talon654.github.io/nkPJNdQIyTOAAO4mqfgP0vyGe-E5Pu6P7UhCIAuEkFqhfbxRQPA-8auUOtjbfhPcihNQ2LH2/
