### ISSUE TITLE
How to set host and port for Firestore Emulator

### ISSUE THREAD

**Issue by vymarkov** [firebase/firebase-tools-ui#506] opened 2021-02-18 13:05 UTC
Hi, I'm working on remote environment (in this case it's ec2 instanse). I found out that firebase hub connect to host and port which were configured by firebase.json, but it's private address, and I need to change it public address.

is it possible? 

![image](https://user-images.githubusercontent.com/1110697/108360843-62e6fd00-71fa-11eb-8b83-8ade4458f901.png)

**Comment by yuchenshi** [comment] 2021-02-18 18:39
Duplicate of #340.

In short, this isn't supported for now and we're still exploring ways to solve this. We do not recommend making emulators listen on the public internet since they're not secure and anyone can see or modify the data. Instead, you can make the emulators locally on EC2 and then set up a proxy (e.g. `ssh -D`) to visit the Emulator UI, which also works around this issue.

**Closed by yuchenshi** 2021-02-18 18:39 UTC
