### ISSUE TITLE
How do I "Please specify these environment variables: GCLOUD_PROJECT FIREBASE_EMULATOR_HUB"?

### ISSUE THREAD

**Issue by varunarora** [firebase/firebase-tools-ui#32] opened 2020-03-13 03:34 UTC
Upon trying to run:
```
firebase emulators:exec --project sample --only database,firestore 'npm start'
```

I get:
```
...
i  Running script: npm start

> firebase-tools-ui@0.1.0 start /mnt/c/Users/varunarora/Code/firebaseui/firebase-tools-ui
> react-scripts start

Please specify these environment variables: GCLOUD_PROJECT FIREBASE_EMULATOR_HUB
(Are you using firebase-tools@>=7.14.0 with `--project your-project`?)
```

I just installed `firebase-tools`, so got version `7.15.0`. Do I need to install a lower version?

I tried to export the env vars to values `EMULATOR_HUB_ENV="FIREBASE_EMULATOR_HUB"` and `GCLOUD_PROJECT="sample"` to no avail (unless there is a fancier node way to set these variables so they are picked up by `react-scripts start`).

**Comment by varunarora** [comment] 2020-03-13 03:52
Downgrading to v`7.6.0` which I picked as low version on the `package.json` here didn't resolve this situation either.

**Comment by yuchenshi** [comment] 2020-03-13 16:20
Hi and thanks for the interest! As you can see, we're still actively working on this project right now so things may be a little bit harder at this point. We're also working on a simpler command to start this. But for now, `firebase emulators:exec` should set the environment variables for you, but for some reason it didn't. Let's figure out why.

Could you please try the following commands and paste the output?

```bash
which firebase
firebase --version
firebase emulators:exec --project sample --only database,firestore 'env'
```

The last one specifically prints out all environment variables, and please look for the two lines with `GCLOUD_PROJECT=...` and `FIREBASE_EMULATOR_HUB=...`

Also, please kindly let us know what platforms you're using (e.g. OS (especially if you're using Bash on Windows or Cygwin), Node.js version and build.)

**Comment by yuchenshi** [comment] 2020-03-13 16:26
Oh and by the way, please use the latest firebase-tools for this project. Try this before the debugging steps above: `npm install -g firebase-tools@latest` (if you installed it through `npm`).

**Comment by varunarora** [comment] 2020-03-14 01:15
Of course, I completely understand, Yuchen! Thank you for the opportunity to share your progress so far with the community.

So I am installing `firebase-tools` in a local directory, so my outputs to the corresponding commands are:

```
$ ../node_modules/firebase-tools/lib/bin/firebase.js --version
7.15.0

$ ../node_modules/firebase-tools/lib/bin/firebase.js emulators:exec --project sample --only database,firestore 'env'

⚠  Could not find config (firebase.json) so using defaults.
i  emulators: Starting emulators: firestore, database
✔  hub: emulator hub started at http://localhost:4400
⚠  firestore: Did not find a Cloud Firestore rules file specified in a firebase.json config file.
⚠  firestore: The emulator will default to allowing all reads and writes. Learn more about this option: https://firebase.google.com/docs/emulator-suite/install_and_configure#security_rules_configuration.
i  firestore: Serving ALL traffic (including WebChannel) on http://localhost:8080
⚠  firestore: Support for WebChannel on a separate port (8081) is DEPRECATED and will go away soon. Please use port above instead.
i  firestore: downloading cloud-firestore-emulator-v1.11.1.jar...
Progress: ==========================================================================================================> (100% of 64MB i  firestore: Removing outdated emulator files: cloud-firestore-emulator-v1.9.0.jar
i  firestore: firestore emulator logging to firestore-debug.log
✔  firestore: firestore emulator started at http://localhost:8080
i  firestore: For testing set FIRESTORE_EMULATOR_HOST=localhost:8080
⚠  database: Did not find a Realtime Database rules file specified in a firebase.json config file.
⚠  database: The emulator will default to allowing all reads and writes. Learn more about this option: https://firebase.google.com/docs/emulator-suite/install_and_configure#security_rules_configuration.
i  database: downloading firebase-database-emulator-v4.4.0.jar...
Progress: ==========================================================================================================> (100% of 28MB i  database: Removing outdated emulator files: firebase-database-emulator-v4.2.0.jar
i  database: database emulator logging to database-debug.log
✔  database: database emulator started at http://localhost:9000
i  database: For testing set FIREBASE_DATABASE_EMULATOR_HOST=localhost:9000
i  Running script: env
LESSOPEN=| /usr/bin/lesspipe %s
USER=varun
LD_LIBRARY_PATH=/usr/local/lib:
SHLVL=1
HOME=/home/varun
OLDPWD=/home/varun/Code/firebaseui
PS1=\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w \[\033[31m\]$(parse_git_branch)\[\033[00m\]$
FIREBASE_DATABASE_EMULATOR_HOST=localhost:9000
FIRESTORE_EMULATOR_HOST=localhost:8080
WSL_DISTRO_NAME=Ubuntu
LOGNAME=varun
NAME=<my computer name>
_=../node_modules/firebase-tools/lib/bin/firebase.js
TERM=xterm-256color
PATH=/home/varun/bin:/home/varun/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Users/varunarora/Downloads/cmder_mini/vendor/conemu-maximus5/ConEmu/Scripts:/mnt/c/Users/varunarora/Downloads/cmder_mini/vendor/conemu-maximus5:/mnt/c/Users/varunarora/Downloads/cmder_mini/vendor/conemu-maximus5/ConEmu:/mnt/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler:/mnt/c/Program Files (x86)/Intel/iCLS Client/:/mnt/c/Program Files/Intel/iCLS Client/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/IntelSGXPSW/bin/x64/Release/:/mnt/c/Program Files/Intel/IntelSGXPSW/bin/win32/Release/:/mnt/c/Program Files/Git/cmd:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Program Files/Intel/WiFi/bin/:/mnt/c/Program Files/Common Files/Intel/WirelessCommon/:/mnt/c/Program Files/Microsoft SQL Server/120/Tools/Binn/:/mnt/c/Program Files/Common Files/Autodesk Shared/:/mnt/c/Users/varunarora/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/varunarora/AppData/Local/atom/bin:/mnt/c/Users/varunarora/AppData/Local/hyper/app-3.0.2/resources/bin:/%USERPROFILE%/AppData/Local/Microsoft/WindowsApps:/snap/bin:/home/varun/bin
LANG=en_US.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
FIREBASE_FIRESTORE_EMULATOR_ADDRESS=localhost:8080
SHELL=/bin/bash
GCLOUD_PROJECT=sample
LESSCLOSE=/usr/bin/lesspipe %s %s
PWD=/home/varun/Code/firebaseui/firebase-tools-ui
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
PYTHONPATH=:/home/varun/Code/opencurriculum/oc/venv-packages/
HOSTTYPE=x86_64
WSLENV=
✔  Script exited successfully (code 0)
i  emulators: Shutting down emulators.
i  hub: Stopping emulator hub
i  firestore: Stopping firestore emulator
i  database: Stopping database emulator
```

So, while `GCLOUD_PROJECT` is set as expected, `FIREBASE_EMULATOR_HUB` is not.

Lastly, I am using bash through ConEmu on Ubuntu 16.04 on WSL. Node JS: v8.14.0.

Am I doing something wrong?

**Comment by yuchenshi** [comment] 2020-03-17 22:58
I don't think you've did anything wrong, but it's weird that the hub started but `FIREBASE_EMULATOR_HUB` is not set. I'll look into the code more, but in the meantime could you please run again with `--debug` and attach the output? Like

```bash
firebase emulators:exec --debug --project sample --only database,firestore 'env'
```

**Comment by varunarora** [comment] 2020-03-18 18:17
Here you go:
```
[2020-03-18T18:12:33.795Z] ----------------------------------------------------------------------
[2020-03-18T18:12:33.800Z] Command:       /usr/bin/node /mnt/c/Users/varunarora/Code/firebaseui/node_modules/firebase-tools/lib/bin/firebase.js emulators:exec --debug --project sample --only database,firestore env
[2020-03-18T18:12:33.801Z] CLI Version:   7.15.0
[2020-03-18T18:12:33.801Z] Platform:      linux
[2020-03-18T18:12:33.802Z] Node Version:  v8.14.0
[2020-03-18T18:12:33.802Z] Time:          Wed Mar 18 2020 11:12:33 GMT-0700 (PDT)
[2020-03-18T18:12:33.803Z] ----------------------------------------------------------------------
[2020-03-18T18:12:33.803Z]
[2020-03-18T18:12:33.895Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2020-03-18T18:12:33.899Z] > authorizing via signed-in user
⚠  Could not find config (firebase.json) so using defaults.
i  emulators: Starting emulators: firestore, database
[2020-03-18T18:12:34.086Z] [hub] writing locator at /tmp/hub-sample.json
✔  hub: emulator hub started at http://localhost:4400
⚠  firestore: Did not find a Cloud Firestore rules file specified in a firebase.json config file.
⚠  firestore: The emulator will default to allowing all reads and writes. Learn more about this option: https://firebase.google.com/docs/emulator-suite/install_and_configure#security_rules_configuration.
i  firestore: Serving ALL traffic (including WebChannel) on http://localhost:8080
⚠  firestore: Support for WebChannel on a separate port (8081) is DEPRECATED and will go away soon. Please use port above instead.
[2020-03-18T18:12:34.191Z] Ignoring unsupported arg: projectId
[2020-03-18T18:12:34.191Z] Ignoring unsupported arg: auto_download
[2020-03-18T18:12:34.192Z] Starting firestore emulator with command {"binary":"java","args":["-Duser.language=en","-jar","/home/varun/.cache/firebase/emulators/cloud-firestore-emulator-v1.11.1.jar","--host","localhost","--port",8080,"--webchannel_port",8081],"optionalArgs":["port","webchannel_port","host","rules","functions_emulator","seed_from_export"],"joinArgs":false}
i  firestore: firestore emulator logging to firestore-debug.log
[2020-03-18T18:12:38.576Z] API endpoint: http://localhost
[2020-03-18T18:12:38.577Z] :8080
If you are using a library that supports the FIRESTORE_EMULATOR_HOST environment variable, run:

   export FIRESTORE_EMULATOR_HOST=localhost:8080

Dev App Server is now running.


✔  firestore: firestore emulator started at http://localhost:8080
i  firestore: For testing set FIRESTORE_EMULATOR_HOST=localhost:8080
⚠  database: Did not find a Realtime Database rules file specified in a firebase.json config file.
⚠  database: The emulator will default to allowing all reads and writes. Learn more about this option: https://firebase.google.com/docs/emulator-suite/install_and_configure#security_rules_configuration.
[2020-03-18T18:12:38.666Z] Ignoring unsupported arg: projectId
[2020-03-18T18:12:38.667Z] Ignoring unsupported arg: auto_download
[2020-03-18T18:12:38.668Z] Starting database emulator with command {"binary":"java","args":["-Duser.language=en","-jar","/home/varun/.cache/firebase/emulators/firebase-database-emulator-v4.4.0.jar","--host","localhost","--port",9000],"optionalArgs":["port","host","functions_emulator_port","functions_emulator_host"],"joinArgs":false}
i  database: database emulator logging to database-debug.log
[2020-03-18T18:12:42.990Z] 11:12:42.987 [NamespaceSystem-akka.actor.default-dispatcher-4] INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger started

[2020-03-18T18:12:43.524Z] 11:12:43.524 [main] INFO com.firebase.server.forge.App$ - Listening at localhost:9000

✔  database: database emulator started at http://localhost:9000
i  database: For testing set FIREBASE_DATABASE_EMULATOR_HOST=localhost:9000
i  Running script: env
[2020-03-18T18:12:43.750Z] Running env with environment {"SHELL":"/bin/bash","TERM":"xterm-256color","WSLENV":"","USER":"varun","NAME":"<computer name>","LD_LIBRARY_PATH":"/usr/local/lib:","LS_COLORS":"rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:","WSL_DISTRO_NAME":"Ubuntu","HOSTTYPE":"x86_64","PATH":"/home/varun/bin:/home/varun/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Users/varunarora/Downloads/cmder_mini/vendor/conemu-maximus5/ConEmu/Scripts:/mnt/c/Users/varunarora/Downloads/cmder_mini/vendor/conemu-maximus5:/mnt/c/Users/varunarora/Downloads/cmder_mini/vendor/conemu-maximus5/ConEmu:/mnt/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler:/mnt/c/Program Files (x86)/Intel/iCLS Client/:/mnt/c/Program Files/Intel/iCLS Client/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/IntelSGXPSW/bin/x64/Release/:/mnt/c/Program Files/Intel/IntelSGXPSW/bin/win32/Release/:/mnt/c/Program Files/Git/cmd:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Program Files/Intel/WiFi/bin/:/mnt/c/Program Files/Common Files/Intel/WirelessCommon/:/mnt/c/Program Files/Microsoft SQL Server/120/Tools/Binn/:/mnt/c/Program Files/Common Files/Autodesk Shared/:/mnt/c/Users/varunarora/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/varunarora/AppData/Local/atom/bin:/mnt/c/Users/varunarora/AppData/Local/hyper/app-3.0.2/resources/bin:/%USERPROFILE%/AppData/Local/Microsoft/WindowsApps:/snap/bin:/home/varun/bin","PWD":"/home/varun/Code/firebaseui/firebase-tools-ui","LANG":"en_US.UTF-8","PS1":"\\[\\033[01;32m\\]\\u@\\h\\[\\033[00m\\]:\\[\\033[01;34m\\]\\w \\[\\033[31m\\]$(parse_git_branch)\\[\\033[00m\\]$ ","SHLVL":"1","HOME":"/home/varun","PYTHONPATH":":/home/varun/Code/opencurriculum/oc/venv-packages/","LOGNAME":"varun","XDG_DATA_DIRS":"/usr/local/share:/usr/share:/var/lib/snapd/desktop","LESSOPEN":"| /usr/bin/lesspipe %s","LESSCLOSE":"/usr/bin/lesspipe %s %s","OLDPWD":"/home/varun","_":"../node_modules/firebase-tools/lib/bin/firebase.js","GCLOUD_PROJECT":"sample","FIREBASE_DATABASE_EMULATOR_HOST":"localhost:9000","FIRESTORE_EMULATOR_HOST":"localhost:8080","FIREBASE_FIRESTORE_EMULATOR_ADDRESS":"localhost:8080"}
LESSOPEN=| /usr/bin/lesspipe %s
USER=varun
LD_LIBRARY_PATH=/usr/local/lib:
SHLVL=1
HOME=/home/varun
OLDPWD=/home/varun
PS1=\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w \[\033[31m\]$(parse_git_branch)\[\033[00m\]$
FIREBASE_DATABASE_EMULATOR_HOST=localhost:9000
FIRESTORE_EMULATOR_HOST=localhost:8080
WSL_DISTRO_NAME=Ubuntu
LOGNAME=varun
NAME=<computer name>
_=../node_modules/firebase-tools/lib/bin/firebase.js
TERM=xterm-256color
PATH=/home/varun/bin:/home/varun/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Users/varunarora/Downloads/cmder_mini/vendor/conemu-maximus5/ConEmu/Scripts:/mnt/c/Users/varunarora/Downloads/cmder_mini/vendor/conemu-maximus5:/mnt/c/Users/varunarora/Downloads/cmder_mini/vendor/conemu-maximus5/ConEmu:/mnt/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler:/mnt/c/Program Files (x86)/Intel/iCLS Client/:/mnt/c/Program Files/Intel/iCLS Client/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/IntelSGXPSW/bin/x64/Release/:/mnt/c/Program Files/Intel/IntelSGXPSW/bin/win32/Release/:/mnt/c/Program Files/Git/cmd:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Program Files/Intel/WiFi/bin/:/mnt/c/Program Files/Common Files/Intel/WirelessCommon/:/mnt/c/Program Files/Microsoft SQL Server/120/Tools/Binn/:/mnt/c/Program Files/Common Files/Autodesk Shared/:/mnt/c/Users/varunarora/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/varunarora/AppData/Local/atom/bin:/mnt/c/Users/varunarora/AppData/Local/hyper/app-3.0.2/resources/bin:/%USERPROFILE%/AppData/Local/Microsoft/WindowsApps:/snap/bin:/home/varun/bin
LANG=en_US.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
FIREBASE_FIRESTORE_EMULATOR_ADDRESS=localhost:8080
SHELL=/bin/bash
GCLOUD_PROJECT=sample
LESSCLOSE=/usr/bin/lesspipe %s %s
PWD=/home/varun/Code/firebaseui/firebase-tools-ui
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
PYTHONPATH=:/home/varun/Code/opencurriculum/oc/venv-packages/
HOSTTYPE=x86_64
WSLENV=
✔  Script exited successfully (code 0)
i  emulators: Shutting down emulators.
i  hub: Stopping emulator hub
i  firestore: Stopping firestore emulator
[2020-03-18T18:12:44.343Z] *** shutting down gRPC server since JVM is shutting down

[2020-03-18T18:12:44.349Z] *** server shut down

i  database: Stopping database emulator
[2020-03-18T18:12:44.362Z] 11:12:44.362 [Thread-1] INFO com.firebase.server.forge.App$ - Attempting graceful shutdown.

[2020-03-18T18:12:44.391Z] 11:12:44.390 [Thread-1] INFO com.firebase.server.forge.App$ - Graceful shutdown complete.
```

**Comment by yuchenshi** [comment] 2020-03-18 18:54
This looks like a regression in firebase CLI v7.15.0 and I've drafted a fix at https://github.com/firebase/firebase-tools/pull/2036

In the meantime, please downgrade to `7.14.0` (but not any earlier version).

Thanks a ton for the report and detailed debugging information -- that helped a lot.

**Comment by varunarora** [comment] 2020-03-19 02:03
Thanks, @yuchenshi! I think we are good here. Please feel free to close.

**Comment by yuchenshi** [comment] 2020-03-19 02:26
Closing since this is actually an issue with firebase-tools and the fix has been merged to master there.

**Closed by yuchenshi** 2020-03-19 02:26 UTC
