### ISSUE TITLE
Can other computer link to the emulator ui?

### ISSUE THREAD

**Issue by hearther** [firebase/firebase-tools-ui#537] opened 2021-03-31 06:57 UTC
Firebase CLI version 9.2.2

I had setup a firebase emulator on mac-mini with following firebase.json

`{
  "database": {
    "rules": "database.rules.json"
  },
  "hosting": {
    "public": "public",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ]
  },
  "emulators": {
    "auth": {
      "port": 9099,
      "host": "0.0.0.0"
    },
    "functions": {
      "port": 5001,
      "host": "0.0.0.0"
    },
    "database": {
      "port": 9000,
      "host": "0.0.0.0"
    },
    "hosting": {
      "port": 5000,
      "host": "0.0.0.0"
    },
    "ui": {
      "enabled": true,
      "host": "0.0.0.0",
      "bindhost":"mac-mini.local"      
    }
  }
}`

Other devices (iOS, android) work fine with functions.
But when I check the RTDB with safari on other mbp.
It failed on tried to connect RTDB and web socket on 127.0.0.1 .

![Firebase_Emulator_Suite](https://user-images.githubusercontent.com/5311606/113102948-3e3a6800-9231-11eb-9069-b2986a580c43.png)

**Comment by yuchenshi** [comment] 2021-03-31 16:31
Duplicate of #340.

**Closed by yuchenshi** 2021-03-31 16:31 UTC
