### ISSUE TITLE
TypeError: Cannot read property 'createUserWithEmailAndPassword' of undefined at data

### ISSUE THREAD

**Issue by ghost** [firebase/firebase-tools-ui#470] opened 2021-01-06 11:33 UTC
I am trying to use firebase emulators: I can see my application at 5000 and auth at 9099 localhosts but the auth emulator is not receiving my data as firebase auth.

I have used this command - "firebase --project="" emulators:start" to start the emulators.

Within the browser logs, I can see a post request is being generated to a URL that contains my API key. When tried to access the API URL manually it gives the below output : 

{
"error": {
"code": 404,
"message": "Not Found",
"errors": [
{
"message": "Not Found",
"reason": "notFound"
}
],
"status": "NOT_FOUND"
}
}

**Comment by yuchenshi** [comment] 2021-01-06 16:13
The Auth emulator requires a non-empty project ID to work properly. May I ask the reason behind `--project ""`?

**Comment by deepalwin** [comment] 2021-01-06 16:52
@yuchenshi thank you for the quick reply. Within my comment i have kept it empty however while actual use i have added the name of my project id within the command. Also the command runs successfully. My application gets hosted on local emulators at port 5000. I can see my auth emulator as well but my data doesn't get transferred to auth emulator

**Comment by strom2357** [comment] 2021-01-09 00:38
To try to troubleshoot the 404 here are there steps you've found or a minimal project we could reproduce this issue with?  Alternatively code for repro can be shared privately via our support channels here https://firebase.google.com/support/troubleshooter/contact

**Comment by deepalwin** [comment] 2021-01-15 10:28
@strom2357 I have hosted my project using this command - firebase --project="{myproject}" emulators:start

Within my HTML File if I use this 
"await firebase.auth().createUserWithEmailAndPassword("example@gmail.com", "password");"  --> In this case it works fine and my email id and password goes to firebase cloud auth. Now the issue is I want to use auth emulators and I am using the below within my code :

"await firebase.auth().useEmulator('http://localhost:9099').createUserWithEmailAndPassword("bebotech@gmail.com", "Bajaj@33");"

This doesn't send my values to the auth emulators. My hosting emulators are working good and the application is hosted on port 5000 using hosting emulators. While I see my web page at port 5000, It says "Running in emulator mode. Do not use with production credentials." but my auth emulators don't take up these values.

Kindly help!

**Comment by yuchenshi** [comment] 2021-01-19 17:04
Hi there! `useEmulator` does not return anything -- it side effects. Have you tried something like this?

```js
firebase.auth().useEmulator('http://localhost:9099');
await firebase.auth().createUserWithEmailAndPassword("example@gmail.com", "password");
```

**Closed** 2022-10-14 00:03 UTC
