### ISSUE TITLE
Firestore data not shown in emulator UI

### ISSUE THREAD

**Issue by burhanrashid52** [firebase/firebase-tools-ui#327] opened 2020-07-13 02:56 UTC
### [REQUIRED] Environment info

**firebase-tools:** 8.4.3

**Platform:** macOS

### [REQUIRED] Test case

I am running the emulator UI locally and connecting my android device to the local emulator UI. I am using following code to connect my firestorm DB from the android device.
```kotlin   
val settings = FirebaseFirestoreSettings.Builder()
                .setHost("10.0.2.2:8080")
                .setSslEnabled(false)
                .setPersistenceEnabled(false)
                .build()

firestoreInstance = FirebaseFirestore.getInstance()
firestoreInstance.firestoreSettings = settings
```
I wanted to test firestore database in my local.

### [REQUIRED] Steps to reproduce

1. Start emulator UI
2. Setup firestore setting in android.
3. Add some data to firestore.

### [REQUIRED] Expected behavior

The data which is added from device should be visible on firestore emulator UI.
http://localhost:4000/firestore

### [REQUIRED] Actual behavior
The data is successfully pushed to the local emulator and got an update on the android device. But the data is not visible firestore emulator UI.
http://localhost:4000/firestore

**Workaround:**
If we paste firestore URL manually on the browser then we are able to see the data.
<img width="1543" alt="Screenshot 2020-07-13 at 8 20 17 AM" src="https://user-images.githubusercontent.com/14251963/87266389-c8477280-c4e2-11ea-894e-cf21aedbe939.png">

As we can see that the document `PRWJQ4Sp...` is visible now. But it is not shown under `users` collection.

**Comment by samtstern** [comment] 2020-07-14 07:28
@burhanrashid52 thanks for filing this!  I am transferring this issue to the `firebase-tools-ui` repo.

**Comment by yuchenshi** [comment] 2020-07-15 22:02
Hi, it's really hard for us to troubleshoot the issue without the actual code snippet for adding data, but I'm guess you're experiencing #273. Please take a look over there and see if that describes your problem. If so, please close this issue and subscribe to that one. If not, please share a code snippet on how the data is added in the Android app.

**Comment by bidipeppercrap** [comment] 2020-08-07 11:16
I got the same proble, no data is shown in firestore emulator, even if I manually pasted the link

**Comment by burhanrashid52** [comment] 2020-09-13 01:56
@yuchenshi I just wanted to understand how the client code snippet will help here. Because I am successfully able to push the data from the client and able to see in the emulator using the workaround by pasting the link the browser. That's mean the client is working properly by pushing the data correctly. Let me know if I am missing something here. Thanks

**Comment by yuchenshi** [comment] 2020-09-14 15:49
The Firestore data viewer in Firebase Emulator UI is far from perfect and sometimes it has bugs showing certain document / collection layouts, notably #273.

We'd appreciate it if you can check if #273 describes what you experience. If not, you may have found a new bug and we'd like some insights on how the data is shaped and documents are added in what order.

**Comment by yuchenshi** [comment] 2020-10-23 18:00
Closing due to inactivity.

**Closed by yuchenshi** 2020-10-23 18:00 UTC
Labels: question

**Comment by rublev** [comment] 2021-01-19 19:31
This is still broken for me and nothing I do except creating the initial collection and subdocument does anything, not setting the project in command line, not doing `firebase use`, nothing. Unreal annoying

**Comment by heyalexchoi** [comment] 2021-01-26 04:19
I am also experiencing this issue. I am reading and writing data in tests, so I know it is reading and writing to the emulator, but I cannot see the data in the emulator UI.

**Comment by burhanrashid52** [comment] 2021-01-26 10:30
@yuchenshi Shall we reopen this?

**Comment by samtstern** [comment] 2021-01-26 10:34
@heyalexchoi @burhanrashid52 if you're reading and writing data to the emulator but can't see it in the UI **check your project IDs**.  The Emulator UI only shows data for one project ID, the one you used to start the emulators with `emulators:start`.  It's likely that your tests or your code are writing to a different project, which would be invisible in the UI.

**Comment by burhanrashid52** [comment] 2021-01-26 11:08
@samtstern Yes, I double-checked. The Project id is the same. As I mentioned in the bug report the workaround,
`If we paste firestore URL manually on the browser then we are able to see the data.` which means it's not able to render changes in real-time.

**Comment by heyalexchoi** [comment] 2021-01-26 21:20
@samtstern @burhanrashid52 updated my comment

**Comment by samtstern** [comment] 2021-01-27 11:01
@burhanrashid52 there are two types of Firestore changes:

- A new collection is added. Neither the Emulator UI or the Firebase console can show these changes in real-time because there is no way to "listen" for them in Firestore.
- A document within an existing collection is added/removed/updated. Both the Emulator UI and the Firebase console can show these in real time.

If you're consistently seeing behavior that doesn't match what I described, please open a new issue and let us know how to reproduce it!

**Comment by brandonhub** [comment] 2021-03-21 23:36
> @heyalexchoi @burhanrashid52 if you're reading and writing data to the emulator but can't see it in the UI **check your project IDs**. The Emulator UI only shows data for one project ID, the one you used to start the emulators with `emulators:start`. It's likely that your tests or your code are writing to a different project, which would be invisible in the UI.

Can't stress this enough. I was moving my dev environment from another remote firebase project to a local one powered by a firebase emulator. My emulator was emulating my **production project** but I was calling `firebase.initializeApp` with my **dev project** API keys/projectIDs/appIDs. That caused some wonky behavior where some reads would work, but writes wouldn't go through (they would return 200 but not update the UI). So anybody having trouble with wonky emulator UI stuff or just emulator behavior in general..._double check your project ids!!!_

**Comment by dadixon** [comment] 2022-02-04 13:20
I'm having the same issue. I can get the authentication working in the emulator UI but the Firestore UI doesn't show any data.

**Comment by loolooii** [comment] 2022-03-26 09:55
First data would show up in Firestore Emulator UI, but somehow it stopped working, and ever since that happened, I can only see the data on the iOS simulator but not in the emulator. It seems they somehow went out of sync. 

I see people having this problem since 2020 and nobody seems to have a real solution for it. This is an obvious bug.

I'm using the FlutterFire CLI, so everything is setup automatically. I just do this:

```
await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  FirebaseFirestore.instance.useFirestoreEmulator('localhost', 8080);
  FirebaseAuth.instance.useAuthEmulator('localhost', 9099);
  FirebaseFirestore.instance.useFirestoreEmulator('localhost', 5001);
```
