### ISSUE TITLE
Error: Did not find any running emulators for project

### ISSUE THREAD

**Issue by DerrickAfrifa** [firebase/firebase-tools-ui#723] opened 2022-03-09 17:22 UTC
I would like to export data from a running emulator. I start the emulators using the following command:
```
firebase emulators:start --import=./firebase-emulator-data
```
I can successfully import the data and view it using the emulator UI.
I then run the command 
```
firebase emulators:export ./firebase-emulator-data
```
However this gives me the error `Did not find any running emulators for project { projectId }`
This is strange because when I run the start command with the `--export-on-exit` flag, this exports my data successfully.
I am running all commands in the same directory using different terminal windows.

Any ideas why the export command says it cannot find running emulators for my project even though my emulators are running for my project (the only project which is the default)?

`firebase-tools: v10.2.2`
`node: v12.20.0`
`OS: macOS Monterey`

**Comment by yuchenshi** [comment] 2022-03-28 20:21
Duplicate of https://github.com/firebase/firebase-tools/issues/4283


We'd appreciate it if you could upload your debug logs there!

**Closed by yuchenshi** 2022-03-28 20:21 UTC
