### ISSUE TITLE
Emulator cannot --export-on-exit when run via npm

### ISSUE THREAD

**Issue by gregfenton** [firebase/firebase-tools-ui#334] opened 2020-08-03 23:50 UTC
Environment:

- MacOS Catalina: 10.15.6
- shell:  zsh 5.7.1
- node: v14.4.0
- npm: 6.14.7

I use an npm script to launch the emulators.  In the `scripts` section of `package.json` I have:

`"emulators": "firebase emulators:start --only firestore --import=./data --export-on-exit"`

The emulators run fine when I run `npm run emulators`.

But when I terminate the command, things do not work as expected.  Pressing `ctrl+c` shows that the emulators receive 2 SIGINTs:

```
^C
i  emulators: Received SIGINT (Ctrl-C) for the first time. Starting a clean shutdown.
i  emulators: Please wait for a clean shutdown or send the SIGINT (Ctrl-C) signal again to stop right now.
i  Automatically exporting data using --export-on-exit "./data" please wait for the export to finish...

⚠  emulators: Received SIGINT (Ctrl-C) 2 times. You have forced the Emulator Suite to exit without waiting for 2 subprocesses to finish. These processes may still be running on your machine:

 ┌────────────────────┬────────────────┬───────┐
 │ Emulator           │ Host:Port      │ PID   │
 ├────────────────────┼────────────────┼───────┤
 │ Emulator UI        │ localhost:4444 │ 87959 │
 ├────────────────────┼────────────────┼───────┤
 │ Firestore Emulator │ localhost:7777 │ 87959 │
 └────────────────────┴────────────────┴───────┘

 To force them to exit run:

 kill 87959 87959
```

It is the warning, about receiving Ctrl-C 2 times, that is the problem.  Because of this issue, the data does not get exported on exit.

Running that same command but directly on the command line rather than via `npm run emulators`, and Ctrl-C shuts the emulators down cleanly and data exports as expected.

**Comment by yuchenshi** [comment] 2020-08-04 16:59
Duplicate of https://github.com/firebase/firebase-tools/issues/2507, fixed by https://github.com/firebase/firebase-tools/pull/2517 (will be released in the next Firebase CLI release).

Also, for your future reference, this is the GitHub repository for Emulator UI. General emulator issues should be filed on the firebase-tools repository instead.

**Closed by yuchenshi** 2020-08-04 16:59 UTC
